### ISSUE TITLE
Rename Skip to Break

### ISSUE THREAD

**Issue by ditansu** [proofit404/stories#141]
`Skip` is understood as skipping the *current* step. Whereas `Break` is understood as stopping the execution of the whole story. IMHO.

**Comment by proofit404** [comment]
How about `Up`, `Continue`, `Next`? It should sound good in the #88 as well. `Rollback(to=Next())` make more sense to me. Thoughts?

**Comment by casio** [comment]
My 2 cents:
`Skip` pretty much confused me, indeed making me think it was skipping the current step.
`Next` seems ok, but in the context of rollback may seem linguistically counter-intuitive: `roll-BACK-to-NEXT`
`Up` hints to continue flow in the _parent_ story.
I like `Continue` as it fits nicely in a `stories` context.

**Comment by proofit404** [comment]
@casio Thanks for the feedback!
What do you think of https://github.com/dry-python/stories/issues/352#issuecomment-613730266 ?
Will it make sense to see something like `return Continue({'token': 'x'})`?
