### ISSUE TITLE
Support OpenTelemetry.

### ISSUE THREAD

**Issue by thedrow** [proofit404/stories#305]
[OpenTelemetry ](https://opentelemetry.io/)is a new upcoming standard for observability.
Currently our history implementation isn't interchangeable. We should explore how to change that to facilitate exporting the history to tools like Prometheus using the [OpenTelemetry SDK](https://github.com/open-telemetry/opentelemetry-python).

In addition, steps may export their own metrics, or have subtraces in them.
We should reflect that as well in our history.

Perhaps we should consider using OpenTelemetry instead of our own history.

This supersedes #103 since OpenTracing is now part of OpenTelemetry.

**Comment by proofit404** [comment]
> Perhaps we should consider using OpenTelemetry instead of our own history.

Definitely no. Contribs can't influence/replace core.
