### ISSUE TITLE
Expose story context to the success result of the story run method.

### ISSUE THREAD

**Issue by proofit404** [proofit404/stories#352]
Stories can be used both as stand-alone objects or substories of other stories.

If we want to return a value from such a story when we run it as a stand-alone object, we have a problem.

We can't use the `Result` class in the story since it'll stop the execution of the parent story when we inject the story.

For example, we have a story like this:
```python
class TokenUseCase:
    @story
    @arguments('user')
    def obtain_token(I):
        I.require_user_active
        I.create_token
        I.return_token

    def require_user_active(self, ctx):
        if ctx.user.is_active:
            return Success()
        return Failure()

    def create_token(self, ctx):
        ctx.token = self.create_user_token(ctx.user)
        return Success()

    def return_token(self, ctx):
        return Result({'token': ctx.token})
```
In this case, we have two options:
1. Split this story into two parts. One will be used as a substory. The other one is the stand-alone wrapper from two steps. One for the story, one for the return statement.
2. Pass a boolean somehow (IoC for example) to the last step to decide what kind of objects we need to return.

Both variants do not bring me joy.

To be clear, **in most cases Result won't be a problem** If we describe the actual process from the business domain, and this process supposed to give us a result, this will be a valid behavior on any level of nesting.

The problem appears only for relatively low-level stuff like tokens. We can't make any business decision at this level of logic, so Result is not suited there by design.

Even it's a relatively rare problem from a business logic perspective, I don't want to force users to write wrappers and pass boolean.

`return_token` should not even exist in this case.

I propose to make available `ctx` object on the successful result of the run method.

This way we'll be able to access the `token` variable when we want to use it as a stand-alone story.

```python
class TokenUseCase:
    @story
    @arguments('user')
    def obtain_token(I):
        I.require_user_active
        I.create_token

    def require_user_active(self, ctx):
        if ctx.user.is_active:
            return Success()
        return Failure()

    def create_token(self, ctx):
        ctx.token = self.create_user_token(ctx.user)
        return Success()

result = TokenUseCase().obtain_token.run(User())
assert result.is_success
assert result.ctx.token == 'abc'
```
I would like to invite @ditansu and @ramidk to discuss this proposal.

**Comment by ditansu** [comment]
@proofit404 that is a fine and elegant solution! So we remove Result from story and to support Result semantic  we have to add flexibility to a Skip(). In  a substory Skip have to support two execution modes (as minimum): 
1. to skip only current story 
2. to skip all stories through including  parent story  too

As variant we could add a some flag into Skip' class constructor to change behavior. 

As optional we could add a some annotation in parent story which describe what result in ctx  we expect from a substory

**Comment by proofit404** [comment]
> As optional we could add a some annotation in parent story which describe what result in ctx we expect from a substory

I think this should be a separate topic. Set expectations on substories is a nice feature to have independent from the result of the substories. I think it could be a continuation of #49

**Comment by proofit404** [comment]
> So we remove Result from a story and to support Result semantic we have to add flexibility to a Skip().

I don't want to change the behavior of `Skip`. I think it should stop the story it was returned from including its substories. The way as it is today.

But we could extend its semantic in a backward-compatible way. For example, we could add an optional value argument to the `Skip`. The same as `Result` have. This value will be returned to the caller of the story if `Skip` was returned from the stand-alone story.

If the story is injected somewhere, the value passed to the `Skip` will be ignored. If you want to access to it in the parent story, put it in the context with assignment expression.

If we agreed on this solution, we need to create a separate issue for it as well. #141 would be a blocker for this issue.

As I said earlier I'm strongly against `return_token` step in the example we use, but anyway

```python
class TokenUseCase:
    @story
    @arguments('user')
    def obtain_token(I):
        I.require_user_active
        I.create_token
        I.return_token

    def return_token(self, ctx):
        return Skip({'token': ctx.token})

>>> TokenUseCase().obtain_token(User())
'abc'

>>> ParentStory(TokenUseCase().obtain_token).do(User())
None
```

**Comment by ditansu** [comment]
@proofit404  You don't want change Skip behavior but right here offer to add value argument to Skip. I'm confused :)  I don't see any profits from passing values as Skip' parameter. I vote to pass any values through  a ctx only. Sure excluding Result cases for backward compability. Also I offer  to extend current Skip behavior (break only local story)  by add a flag to  Skip for break whole stories composition. Last offer is optional, because I've checked my stories and understood what the current Skip  behavior (breack local story) and your new offer to end story by last step is quite enough for me.

**Comment by proofit404** [comment]
> I don't want to change the behavior of Skip. I think it should stop the story it was returned from including its substories. The way as it is today.

From the point of view how it affects an execution flow of the story.

> I vote to pass any values through a ctx only.

The context will be the single source of truth inside the story. But you will be able to use `Skip(ctx.foo)` to use `foo` as a result value if it was returned by the outermost story in the composition. If it was returned by a nested story, the `value` argument will be ignored and the context object will be only one way to pass values from substory to the story.

**Comment by proofit404** [comment]
@ditansu From what I understand, you'll be happy with the origin proposal from this issue.

**Comment by ramidk** [comment]
> I propose to make available ctx object on the successful result of the run method.

This seems to do the job and I vote for this one =)
> The context will be the single source of truth inside the story. But you will be able to use `Skip(ctx.foo)` to use `foo` as a result value if it was returned by the outermost story in the composition. If it was returned by a nested story, the `value` argument will be ignored and the context object will be only one way to pass values from substory to the story.

Besides, I like the explicitly of Skip({'token': ctx.token}), but this duality is kinda confusing.

**Comment by proofit404** [comment]
@ramidk thanks for the feedback.

If `Skip` object will have `Next` name, will it make sense to add `value` argument to it?

**Comment by proofit404** [comment]
Superseded by #627
