### ISSUE TITLE
Django Debug Toolbar: TemplateDoesNotExist

### ISSUE THREAD

**Issue by gregbrowndev** [proofit404/stories#391]
Hi, 

I'm seeing an error while trying to enable the Django Debug Toolbar integration:

```
django.template.exceptions.TemplateDoesNotExist: stories/debug_toolbar/stories_panel.html
```

I have the extension listed in `INSTALLED_APPS` as per the docs:

```py
INSTALLED_APPS += [
    "debug_toolbar",
    "stories.contrib.debug_toolbars.django",
]
```

I see the app listed in `get_app_configs()`:

 ```py
from django.apps import apps
stories_ddt = next(config for config in apps.get_app_configs() if 'stories' in config.name)

# out: <AppConfig: django>
```

However, I don't see the template directory listed:

```py
from django.template.utils import get_app_template_dirs
print([dir for dir in get_app_template_dirs('templates') if 'stories' in dir])

# out: []
```

Debugging a little deeper into `get_app_template_dirs` shows:

```py
template_dirs = [
        str(Path(app_config.path) / dirname)
        for app_config in apps.get_app_configs()
        if app_config.path and (Path(app_config.path) / dirname).is_dir()
    ]
```

The template directory is filtered out as `Path(app_config.path) / dirname` resolves to:

`'...python3.8/site-packages/stories/contrib/debug_toolbars/templates'`

which doesn't exist. It should be `debug_toolbars/django/templates`.

**Comment by proofit404** [comment]
Hi,

Thank you for the report!

What version of Django and Django Debug Toolbar you're using?

Have a good day! :tada: 

Best regards,
Artem.

**Comment by gregbrowndev** [comment]
Hi @proofit404,

Django version: 2.2.12
DDT: 2.2

Cheers!

**Comment by proofit404** [comment]
Superseded by https://github.com/proofit404/stories/issues/561
