### ISSUE TITLE
Migrate to personal account.

### ISSUE THREAD

**Issue by proofit404** [proofit404/stories#394]

**Comment by gtors** [comment]
Why? What happened?

**Comment by proofit404** [comment]
I have my family and a full-time job. It obvious to have a restricted amount of free time to spent on open source.

`dry-python` is a brand. And it involves a lot of activities like media appearance, promotion, a news feed, etc.

All these activities have nothing in common with "write a nice library and post it on Reddit".

From that perspective, I decided to use my free time on the fun part of open source.

It's that simple :smile:
