### ISSUE TITLE
How to get colleagues interested in using stories?

### ISSUE THREAD

**Issue by DjaPy** [proofit404/stories#567]
Hi.
 Do you have any tips on how to present the stories library correctly? Any more advanced usage examples? Or you can recommend a strategy. I'm planning to make a presentation. But I don't know where to start yet.

**Comment by proofit404** [comment]
Hello, thanks for using `stories`!

As always it depends from the situation you're in.

If you have a lot of technical debt in your project and you want a technology to get control on the situation, you could propose `stories` as a library which will help the team moves in the right direction.

You can present to the team starting with problems you have:

* a lot of implicit business rules in random places in the code base
* high coupling and low cohesion in the code base
* as a result problems with refactoring
* long time to onboard new members

`stories` library will help you to organize code in an opposite way: 

* Separate state, implementation and specification.
* Clean flow in the source code.
* Each step knows nothing about a neighbor.
* Easy reuse of code.

Try to integrate new library in the gradual way:

* only new features will be written in the new way (with stories or manually)
* don't use all the features from the beginning (no failure protocols, no context contract)
* don't start with IoC from the begging (write implementation in-place in steps without `dependencies`)

I hope you'll convince them to look for code quality in your project with `stories` library or not.

Best regards, Artem.
